#!/bin/bash

if [ "$1" = "clean" ]; then
	rm -rf data/*
	exit 0
fi

mkdir -p data 2>&1 > /dev/null

for scheduler in 2 3; do
	for mode in TCP UDP; do
		for bw in 0.5 1 2 3; do
			echo "topoType:MultiIf
leftSubnet:11.0.
rightSubnet:11.2.
#path_x:delay,queueSize(may be calc),bw(Mb),loss
path_0:10,1000,1,0
path_1:20,1000,$bw,0
path_3:1,1000,10,0" > conf

			echo "xpType:itg
vpnSubnet:20.0.
script:script.itg
scheduler:$scheduler 100" > xp

			for bwi in 80 160 240; do
				echo "-a 20.0.0.1 -T $mode -t 60000 -c 781.25 -C $bwi" > script.itg

				for i in {0..10}; do
					DIR=data/$mode-$scheduler-$bw-$bwi-$i
					if [ -d $DIR ] && [ "$1" != "force" ]; then
						echo "$DIR exists... Skipping!"
					else
						while [ ! -f lab.log ] || [ $(grep "Error" lab.log -c) -gt 0 ]; do
							echo "Running $mode experiment with sched°$scheduler, B@$bw Mbps and ITG@$bwi p/s... Run $i"
							./mpPerf.py -t conf -x xp > lab.log
							ps -aef | grep controller | awk '{ print $2}' | sudo xargs kill
						done

						mkdir -p $DIR
						mv -f {{client,server}.{pcap,log,err},{lab,command}.log,ITG{client,server}.log} $DIR  2>&1 > /dev/null
					fi
				done
			done
		done
	done
done

if [ "$1" = "archive" ]; then
	mkdir -p Archives 2>&1 > /dev/null
	tar czf Archives/usageVSbwVSbw.tar.gz data
fi
